package com.code.algos.bits;

/**
 * You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
 * @author sukh
 *
 */
public class FindTheDifference_1_389 {

  /**
   * Time: O(s+t)<br>
   * Space: O(1)
   * @param s
   * @param t
   * @return
   */
  public char findTheDiff(String s, String t) {
    char ch = 0;
    for (int i = 0; i < s.length(); i++) {
      ch ^= s.charAt(i);
    }

    for (int i = 0; i < t.length(); i++) {
      ch ^= t.charAt(i);
    }

    return ch;
  }

}
